In [5]:
# importing needed packages
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#read in Central Valley csvs from external drive
#path1 = '/Volumes/disk1/Central Valley Fog/4205333.csv'
#path2 = '/Volumes/disk1/Central Valley Fog/4206426.csv'
#path3 = '/Volumes/disk1/Central Valley Fog/4206427.csv'
#path1 = 'E:/Central Valley Fog/4205333.csv'
#path2 = 'E:/Central Valley Fog/4206426.csv'
#path3 = 'E:/Central Valley Fog/4206427.csv'

path1 = 'E:/Central Valley Fog/Sac data/4341535.csv'
path2 = 'E:/Central Valley Fog/Sac data/4341537.csv'

In [7]:
for path in [path1, path2]:
    df = pd.read_csv(path, nrows=0, low_memory=False)
    print(f"{path}:")
    print(df.columns.tolist())
    print()

E:/Central Valley Fog/Sac data/4341535.csv:
['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'REPORT_TYPE', 'SOURCE', 'BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName', 'CoolingDegreeDaysSeasonToDate', 'DailyAverageDewPointTemperature', 'DailyAverageDryBulbTemperature', 'DailyAverageRelativeHumidity', 'DailyAverageSeaLevelPressure', 'DailyAverageStationPressure', 'DailyAverageWetBulbTemperature', 'DailyAverageWindSpeed', 'DailyCoolingDegreeDays', 'DailyDepartureFromNormalAverageTemperature', 'DailyHeatingDegreeDays', 'DailyMaximumDryBulbTemperature', 'DailyMinimumDryBulbTemperature', 'DailyPeakWindDirection', 'DailyPeakWindSpeed', 'DailyPrecipitation', 'DailySnowDepth', 'DailySnowfall', 'DailySustainedWindDirection', 'DailySustainedWindSpeed', 'DailyWeather', 'HeatingDegreeDaysSeasonToDate', 'HourlyAltimeterSetting', 'HourlyDewPointTemperature', 'HourlyDryBulbTemperature', 'HourlyPrecipitation', 'HourlyPresentWeatherType', 'HourlyPressureChange', 'HourlyPressureTendency', 'HourlyRelativeHumidity', 'HourlySeaLevelPressure', 'HourlySkyConditions', 'HourlyStationPressure', 'HourlyVisibility', 'HourlyWetBulbTemperature', 'HourlyWindDirection', 'HourlyWindGustSpeed', 'HourlyWindSpeed', 'MonthlyAverageRH', 'MonthlyAverageWindSpeed', 'MonthlyCoolingDegreeDays', 'MonthlyDaysWithGT001Precip', 'MonthlyDaysWithGT010Precip', 'MonthlyDaysWithGT32Temp', 'MonthlyDaysWithGT90Temp', 'MonthlyDaysWithLT0Temp', 'MonthlyDaysWithLT32Temp', 'MonthlyDepartureFromNormalAverageTemperature', 'MonthlyDepartureFromNormalCoolingDegreeDays', 'MonthlyDepartureFromNormalHeatingDegreeDays', 'MonthlyDepartureFromNormalMaximumTemperature', 'MonthlyDepartureFromNormalMinimumTemperature', 'MonthlyDepartureFromNormalPrecipitation', 'MonthlyDewpointTemperature', 'MonthlyGreatestPrecip', 'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth', 'MonthlyGreatestSnowDepthDate', 'MonthlyGreatestSnowfall', 'MonthlyGreatestSnowfallDate', 'MonthlyHeatingDegreeDays', 'MonthlyMaxSeaLevelPressureValue', 'MonthlyMaxSeaLevelPressureValueDate', 'MonthlyMaxSeaLevelPressureValueTime', 'MonthlyMaximumTemperature', 'MonthlyMeanTemperature', 'MonthlyMinSeaLevelPressureValue', 'MonthlyMinSeaLevelPressureValueDate', 'MonthlyMinSeaLevelPressureValueTime', 'MonthlyMinimumTemperature', 'MonthlyNumberDaysWithHeavyFog', 'MonthlyNumberDaysWithSnowfall', 'MonthlyNumberDaysWithThunderstorms', 'MonthlySeaLevelPressure', 'MonthlyStationPressure', 'MonthlyTotalLiquidPrecipitation', 'MonthlyTotalSnowfall', 'MonthlyWetBulb', 'NormalsCoolingDegreeDay', 'NormalsHeatingDegreeDay', 'REM', 'REPORT_TYPE.1', 'SOURCE.1', 'ShortDurationEndDate005', 'ShortDurationEndDate010', 'ShortDurationEndDate015', 'ShortDurationEndDate020', 'ShortDurationEndDate030', 'ShortDurationEndDate045', 'ShortDurationEndDate060', 'ShortDurationEndDate080', 'ShortDurationEndDate100', 'ShortDurationEndDate120', 'ShortDurationEndDate150', 'ShortDurationEndDate180', 'ShortDurationPrecipitationValue005', 'ShortDurationPrecipitationValue010', 'ShortDurationPrecipitationValue015', 'ShortDurationPrecipitationValue020', 'ShortDurationPrecipitationValue030', 'ShortDurationPrecipitationValue045', 'ShortDurationPrecipitationValue060', 'ShortDurationPrecipitationValue080', 'ShortDurationPrecipitationValue100', 'ShortDurationPrecipitationValue120', 'ShortDurationPrecipitationValue150', 'ShortDurationPrecipitationValue180', 'Sunrise', 'Sunset', 'WindEquipmentChangeDate']

E:/Central Valley Fog/Sac data/4341537.csv:
['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'REPORT_TYPE', 'SOURCE', 'BackupDirection', 'BackupDistance', 'BackupDistanceUnit', 'BackupElements', 'BackupElevation', 'BackupEquipment', 'BackupLatitude', 'BackupLongitude', 'BackupName', 'CoolingDegreeDaysSeasonToDate', 'DailyAverageDewPointTemperature', 'DailyAverageDryBulbTemperature', 'DailyAverageRelativeHumidity', 'DailyAverageSeaLevelPressure', 'DailyAverageStationPressure', 'DailyAverageWetBulbTemperature', 'DailyAverageWindSpeed', 'DailyCoolingDegreeDays', 'DailyDepartureFromNormalAverageTemperature', 'DailyHeatingDegreeDays', 'DailyMaximumDryBulbTemperature', 'DailyMinimumDryBulbTemperature', 'DailyPeakWindDirection', 'DailyPeakWindSpeed', 'DailyPrecipitation', 'DailySnowDepth', 'DailySnowfall', 'DailySustainedWindDirection', 'DailySustainedWindSpeed', 'DailyWeather', 'HeatingDegreeDaysSeasonToDate', 'HourlyAltimeterSetting', 'HourlyDewPointTemperature', 'HourlyDryBulbTemperature', 'HourlyPrecipitation', 'HourlyPresentWeatherType', 'HourlyPressureChange', 'HourlyPressureTendency', 'HourlyRelativeHumidity', 'HourlySeaLevelPressure', 'HourlySkyConditions', 'HourlyStationPressure', 'HourlyVisibility', 'HourlyWetBulbTemperature', 'HourlyWindDirection', 'HourlyWindGustSpeed', 'HourlyWindSpeed', 'MonthlyAverageRH', 'MonthlyAverageWindSpeed', 'MonthlyCoolingDegreeDays', 'MonthlyDaysWithGT001Precip', 'MonthlyDaysWithGT010Precip', 'MonthlyDaysWithGT32Temp', 'MonthlyDaysWithGT90Temp', 'MonthlyDaysWithLT0Temp', 'MonthlyDaysWithLT32Temp', 'MonthlyDepartureFromNormalAverageTemperature', 'MonthlyDepartureFromNormalCoolingDegreeDays', 'MonthlyDepartureFromNormalHeatingDegreeDays', 'MonthlyDepartureFromNormalMaximumTemperature', 'MonthlyDepartureFromNormalMinimumTemperature', 'MonthlyDepartureFromNormalPrecipitation', 'MonthlyDewpointTemperature', 'MonthlyGreatestPrecip', 'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth', 'MonthlyGreatestSnowDepthDate', 'MonthlyGreatestSnowfall', 'MonthlyGreatestSnowfallDate', 'MonthlyHeatingDegreeDays', 'MonthlyMaxSeaLevelPressureValue', 'MonthlyMaxSeaLevelPressureValueDate', 'MonthlyMaxSeaLevelPressureValueTime', 'MonthlyMaximumTemperature', 'MonthlyMeanTemperature', 'MonthlyMinSeaLevelPressureValue', 'MonthlyMinSeaLevelPressureValueDate', 'MonthlyMinSeaLevelPressureValueTime', 'MonthlyMinimumTemperature', 'MonthlyNumberDaysWithHeavyFog', 'MonthlyNumberDaysWithSnowfall', 'MonthlyNumberDaysWithThunderstorms', 'MonthlySeaLevelPressure', 'MonthlyStationPressure', 'MonthlyTotalLiquidPrecipitation', 'MonthlyTotalSnowfall', 'MonthlyWetBulb', 'NormalsCoolingDegreeDay', 'NormalsHeatingDegreeDay', 'REM', 'REPORT_TYPE.1', 'SOURCE.1', 'ShortDurationEndDate005', 'ShortDurationEndDate010', 'ShortDurationEndDate015', 'ShortDurationEndDate020', 'ShortDurationEndDate030', 'ShortDurationEndDate045', 'ShortDurationEndDate060', 'ShortDurationEndDate080', 'ShortDurationEndDate100', 'ShortDurationEndDate120', 'ShortDurationEndDate150', 'ShortDurationEndDate180', 'ShortDurationPrecipitationValue005', 'ShortDurationPrecipitationValue010', 'ShortDurationPrecipitationValue015', 'ShortDurationPrecipitationValue020', 'ShortDurationPrecipitationValue030', 'ShortDurationPrecipitationValue045', 'ShortDurationPrecipitationValue060', 'ShortDurationPrecipitationValue080', 'ShortDurationPrecipitationValue100', 'ShortDurationPrecipitationValue120', 'ShortDurationPrecipitationValue150', 'ShortDurationPrecipitationValue180', 'Sunrise', 'Sunset', 'WindEquipmentChangeDate']

In [8]:
# create dataframes with only the columns we need
# units: HourlyVisibility: km to thousandths, HourlyPrecipitation: mm to tenths

df1 = pd.read_csv(path1, usecols=['STATION', 'DATE', 'REPORT_TYPE', 'LATITUDE', 'LONGITUDE', 'HourlyVisibility','HourlyPrecipitation','HourlyDryBulbTemperature','HourlyDewPointTemperature', 'HourlyWindDirection', 'HourlyWindSpeed', 'MonthlyNumberDaysWithHeavyFog'],low_memory=False)
df2 = pd.read_csv(path2, usecols=['STATION', 'DATE', 'REPORT_TYPE', 'LATITUDE', 'LONGITUDE', 'HourlyVisibility','HourlyPrecipitation','HourlyDryBulbTemperature','HourlyDewPointTemperature', 'HourlyWindDirection', 'HourlyWindSpeed', 'MonthlyNumberDaysWithHeavyFog'],low_memory=False)
# df1 = pd.read_csv(path1, usecols=['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'HourlyVisibility','HourlyPrecipitation','MonthlyNumberDaysWithHeavyFog'],low_memory=False)
# df2 = pd.read_csv(path2, usecols=['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'HourlyVisibility','HourlyPrecipitation','MonthlyNumberDaysWithHeavyFog'],low_memory=False)
#df3 = pd.read_csv(path3, usecols=['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'DailySustainedWindDirection', 'HourlyVisibility','HourlyPrecipitation','MonthlyNumberDaysWithHeavyFog'],low_memory=False)

In [9]:
#check
df1.head()

,STATION,LATITUDE,LONGITUDE,DATE,REPORT_TYPE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyVisibility,HourlyWindDirection,HourlyWindSpeed,MonthlyNumberDaysWithHeavyFog
0,USM00074917,35.117,-119.3,1941-12-01T00:00:00,SAO,11.9,13.0,NaN,160.000,NaN,0.0,NaN
1,USM00074917,35.117,-119.3,1941-12-01T01:00:00,SAO,10.7,12.4,NaN,160.000,158.0,0.5,NaN
2,USM00074917,35.117,-119.3,1941-12-01T02:00:00,SAO,11.3,12.4,NaN,160.000,NaN,0.0,NaN
3,USM00074917,35.117,-119.3,1941-12-01T03:00:00,SAO,11.3,12.4,NaN,160.000,225.0,0.5,NaN
4,USM00074917,35.117,-119.3,1941-12-01T04:00:00,SAO,11.9,13.0,NaN,160.000,225.0,0.5,NaN

In [10]:
df1.head()

,STATION,LATITUDE,LONGITUDE,DATE,REPORT_TYPE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyVisibility,HourlyWindDirection,HourlyWindSpeed,MonthlyNumberDaysWithHeavyFog
0,USM00074917,35.117,-119.3,1941-12-01T00:00:00,SAO,11.9,13.0,NaN,160.000,NaN,0.0,NaN
1,USM00074917,35.117,-119.3,1941-12-01T01:00:00,SAO,10.7,12.4,NaN,160.000,158.0,0.5,NaN
2,USM00074917,35.117,-119.3,1941-12-01T02:00:00,SAO,11.3,12.4,NaN,160.000,NaN,0.0,NaN
3,USM00074917,35.117,-119.3,1941-12-01T03:00:00,SAO,11.3,12.4,NaN,160.000,225.0,0.5,NaN
4,USM00074917,35.117,-119.3,1941-12-01T04:00:00,SAO,11.9,13.0,NaN,160.000,225.0,0.5,NaN

In [11]:
# print all column names
for col in df1.columns:
    print(col)

STATION
LATITUDE
LONGITUDE
DATE
REPORT_TYPE
HourlyDewPointTemperature
HourlyDryBulbTemperature
HourlyPrecipitation
HourlyVisibility
HourlyWindDirection
HourlyWindSpeed
MonthlyNumberDaysWithHeavyFog

In [12]:
#df_list = [df1, df2, df3] 
df_list = [df1, df2] 

# concatenate the dataframes into one
CV_data = pd.concat(df_list, ignore_index = True)

print(CV_data.head(15))

        STATION  LATITUDE  LONGITUDE                 DATE REPORT_TYPE  \
0   USM00074917    35.117     -119.3  1941-12-01T00:00:00         SAO
1   USM00074917    35.117     -119.3  1941-12-01T01:00:00         SAO
2   USM00074917    35.117     -119.3  1941-12-01T02:00:00         SAO
3   USM00074917    35.117     -119.3  1941-12-01T03:00:00         SAO
4   USM00074917    35.117     -119.3  1941-12-01T04:00:00         SAO
5   USM00074917    35.117     -119.3  1941-12-01T05:00:00         SAO
6   USM00074917    35.117     -119.3  1941-12-01T06:00:00         SAO
7   USM00074917    35.117     -119.3  1941-12-01T07:00:00         SAO
8   USM00074917    35.117     -119.3  1941-12-01T08:00:00         SAO
9   USM00074917    35.117     -119.3  1941-12-01T09:00:00         SAO
10  USM00074917    35.117     -119.3  1941-12-01T10:00:00         SAO
11  USM00074917    35.117     -119.3  1941-12-01T11:00:00         SAO
12  USM00074917    35.117     -119.3  1941-12-01T12:00:00         SAO
13  USM00074917    35.117     -119.3  1941-12-01T13:00:00         SAO
14  USM00074917    35.117     -119.3  1941-12-01T14:00:00         SAO

    HourlyDewPointTemperature  HourlyDryBulbTemperature HourlyPrecipitation  \
0                        11.9                      13.0                 NaN
1                        10.7                      12.4                 NaN
2                        11.3                      12.4                 NaN
3                        11.3                      12.4                 NaN
4                        11.9                      13.0                 NaN
5                        11.9                      13.0                 NaN
6                        11.9                      11.9                 NaN
7                        11.9                      11.9                 NaN
8                        11.9                      11.9                 NaN
9                        11.9                      11.9                 NaN
10                       12.4                      13.5                 NaN
11                       13.0                      15.7                 NaN
12                       12.4                      15.7                 NaN
13                       11.9                      18.0                 NaN
14                       11.9                      18.0                 NaN

   HourlyVisibility HourlyWindDirection HourlyWindSpeed  \
0           160.000                 NaN             0.0
1           160.000               158.0             0.5
2           160.000                 NaN             0.0
3           160.000               225.0             0.5
4           160.000               225.0             0.5
5           160.000                 NaN             0.0
6             0.200                45.0             0.5
7             0.000               315.0             0.5
8             0.000                90.0             0.5
9             0.200                 NaN             0.0
10            0.800               158.0             0.5
11            6.400                 NaN             0.0
12            8.000                 NaN             0.0
13            9.600                90.0             1.0
14           12.800               360.0             1.5

    MonthlyNumberDaysWithHeavyFog
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
5                             NaN
6                             NaN
7                             NaN
8                             NaN
9                             NaN
10                            NaN
11                            NaN
12                            NaN
13                            NaN
14                            NaN

In [13]:
# convert HourlyVisibility, HourlyDewPointTemperature, and HourlyDryBulbTemperature to numeric, coercing errors to NaN
CV_data["HourlyVisibility"] = pd.to_numeric(CV_data["HourlyVisibility"], errors="coerce")
CV_data['HourlyDewPointTemperature'] = pd.to_numeric(CV_data['HourlyDewPointTemperature'], errors='coerce')
CV_data['HourlyDryBulbTemperature'] = pd.to_numeric(CV_data['HourlyDryBulbTemperature'], errors='coerce')
CV_data['HourlyWindSpeed'] = pd.to_numeric(CV_data['HourlyWindSpeed'], errors='coerce')
CV_data['HourlyWindDirection'] = pd.to_numeric(CV_data['HourlyWindDirection'], errors='coerce')
CV_data['HourlyPrecipitation'] = pd.to_numeric(CV_data['HourlyPrecipitation'], errors='coerce')

# vis_nonpos = CV_data_filtered[CV_data_filtered["HourlyVisibility"] <= 0]
# print(f"Rows with HourlyVisibility <= 0: {len(vis_nonpos)}")
# vis_nonpos.head(100)

CV_data.head(15)

,STATION,LATITUDE,LONGITUDE,DATE,REPORT_TYPE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyVisibility,HourlyWindDirection,HourlyWindSpeed,MonthlyNumberDaysWithHeavyFog
0,USM00074917,35.117,-119.3,1941-12-01T00:00:00,SAO,11.9,13.0,NaN,160.0,NaN,0.0,NaN
1,USM00074917,35.117,-119.3,1941-12-01T01:00:00,SAO,10.7,12.4,NaN,160.0,158.0,0.5,NaN
2,USM00074917,35.117,-119.3,1941-12-01T02:00:00,SAO,11.3,12.4,NaN,160.0,NaN,0.0,NaN
3,USM00074917,35.117,-119.3,1941-12-01T03:00:00,SAO,11.3,12.4,NaN,160.0,225.0,0.5,NaN
4,USM00074917,35.117,-119.3,1941-12-01T04:00:00,SAO,11.9,13.0,NaN,160.0,225.0,0.5,NaN
5,USM00074917,35.117,-119.3,1941-12-01T05:00:00,SAO,11.9,13.0,NaN,160.0,NaN,0.0,NaN
6,USM00074917,35.117,-119.3,1941-12-01T06:00:00,SAO,11.9,11.9,NaN,0.2,45.0,0.5,NaN
7,USM00074917,35.117,-119.3,1941-12-01T07:00:00,SAO,11.9,11.9,NaN,0.0,315.0,0.5,NaN
8,USM00074917,35.117,-119.3,1941-12-01T08:00:00,SAO,11.9,11.9,NaN,0.0,90.0,0.5,NaN
9,USM00074917,35.117,-119.3,1941-12-01T09:00:00,SAO,11.9,11.9,NaN,0.2,NaN,0.0,NaN
10,USM00074917,35.117,-119.3,1941-12-01T10:00:00,SAO,12.4,13.5,NaN,0.8,158.0,0.5,NaN
11,USM00074917,35.117,-119.3,1941-12-01T11:00:00,SAO,13.0,15.7,NaN,6.4,NaN,0.0,NaN
12,USM00074917,35.117,-119.3,1941-12-01T12:00:00,SAO,12.4,15.7,NaN,8.0,NaN,0.0,NaN
13,USM00074917,35.117,-119.3,1941-12-01T13:00:00,SAO,11.9,18.0,NaN,9.6,90.0,1.0,NaN
14,USM00074917,35.117,-119.3,1941-12-01T14:00:00,SAO,11.9,18.0,NaN,12.8,360.0,1.5,NaN

In [14]:
# fill in missing values for HourlyWindDirection and HourlyWindSpeed with 0
# CV_data["HourlyVisibility"] = CV_data["HourlyVisibility"].fillna(16.000)
CV_data["HourlyWindDirection"] = CV_data["HourlyWindDirection"].fillna(0)
CV_data["HourlyWindSpeed"] = CV_data["HourlyWindSpeed"].fillna(0)
CV_data["HourlyPrecipitation"] = CV_data["HourlyPrecipitation"].fillna(0)

CV_data.head(15)

,STATION,LATITUDE,LONGITUDE,DATE,REPORT_TYPE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyVisibility,HourlyWindDirection,HourlyWindSpeed,MonthlyNumberDaysWithHeavyFog
0,USM00074917,35.117,-119.3,1941-12-01T00:00:00,SAO,11.9,13.0,0.0,160.0,0.0,0.0,NaN
1,USM00074917,35.117,-119.3,1941-12-01T01:00:00,SAO,10.7,12.4,0.0,160.0,158.0,0.5,NaN
2,USM00074917,35.117,-119.3,1941-12-01T02:00:00,SAO,11.3,12.4,0.0,160.0,0.0,0.0,NaN
3,USM00074917,35.117,-119.3,1941-12-01T03:00:00,SAO,11.3,12.4,0.0,160.0,225.0,0.5,NaN
4,USM00074917,35.117,-119.3,1941-12-01T04:00:00,SAO,11.9,13.0,0.0,160.0,225.0,0.5,NaN
5,USM00074917,35.117,-119.3,1941-12-01T05:00:00,SAO,11.9,13.0,0.0,160.0,0.0,0.0,NaN
6,USM00074917,35.117,-119.3,1941-12-01T06:00:00,SAO,11.9,11.9,0.0,0.2,45.0,0.5,NaN
7,USM00074917,35.117,-119.3,1941-12-01T07:00:00,SAO,11.9,11.9,0.0,0.0,315.0,0.5,NaN
8,USM00074917,35.117,-119.3,1941-12-01T08:00:00,SAO,11.9,11.9,0.0,0.0,90.0,0.5,NaN
9,USM00074917,35.117,-119.3,1941-12-01T09:00:00,SAO,11.9,11.9,0.0,0.2,0.0,0.0,NaN
10,USM00074917,35.117,-119.3,1941-12-01T10:00:00,SAO,12.4,13.5,0.0,0.8,158.0,0.5,NaN
11,USM00074917,35.117,-119.3,1941-12-01T11:00:00,SAO,13.0,15.7,0.0,6.4,0.0,0.0,NaN
12,USM00074917,35.117,-119.3,1941-12-01T12:00:00,SAO,12.4,15.7,0.0,8.0,0.0,0.0,NaN
13,USM00074917,35.117,-119.3,1941-12-01T13:00:00,SAO,11.9,18.0,0.0,9.6,90.0,1.0,NaN
14,USM00074917,35.117,-119.3,1941-12-01T14:00:00,SAO,11.9,18.0,0.0,12.8,360.0,1.5,NaN

In [15]:
# Cap visibilities over 16.000 km to 16.000 km in CV_rows
CV_data['HourlyVisibility'] = CV_data['HourlyVisibility'].clip(upper=16.000)

print("CV_data after capping visibility at 16.000 km:")
print(f"Max visibility: {CV_data['HourlyVisibility'].max()}")
print(f"Min visibility: {CV_data['HourlyVisibility'].min()}")

CV_data after capping visibility at 16.000 km:
Max visibility: 16.0
Min visibility: 0.0

In [16]:
# # Cap visibilities over 16.093 km to 16.093 km in CV_rows
# CV_data_filtered['HourlyVisibility'] = CV_data_filtered['HourlyVisibility'].clip(upper=16.093)

# print("CV_data_filtered after capping visibility at 16.093 km:")
# print(f"Max visibility: {CV_data_filtered['HourlyVisibility'].max()}")
# print(f"Min visibility: {CV_data_filtered['HourlyVisibility'].min()}")

In [17]:
# convert date column to datetime format
CV_data["DATE"] = pd.to_datetime(CV_data["DATE"])

In [18]:
# extract year and month from date column and add as new columns
CV_data["year"] = CV_data["DATE"].dt.year
CV_data["month"] = CV_data["DATE"].dt.month
CV_data["day"] = CV_data["DATE"].dt.day
CV_data["hour"] = CV_data["DATE"].dt.hour
CV_data["minute"] = CV_data["DATE"].dt.minute
print(CV_data.head(15))

        STATION  LATITUDE  LONGITUDE                DATE REPORT_TYPE  \
0   USM00074917    35.117     -119.3 1941-12-01 00:00:00         SAO
1   USM00074917    35.117     -119.3 1941-12-01 01:00:00         SAO
2   USM00074917    35.117     -119.3 1941-12-01 02:00:00         SAO
3   USM00074917    35.117     -119.3 1941-12-01 03:00:00         SAO
4   USM00074917    35.117     -119.3 1941-12-01 04:00:00         SAO
5   USM00074917    35.117     -119.3 1941-12-01 05:00:00         SAO
6   USM00074917    35.117     -119.3 1941-12-01 06:00:00         SAO
7   USM00074917    35.117     -119.3 1941-12-01 07:00:00         SAO
8   USM00074917    35.117     -119.3 1941-12-01 08:00:00         SAO
9   USM00074917    35.117     -119.3 1941-12-01 09:00:00         SAO
10  USM00074917    35.117     -119.3 1941-12-01 10:00:00         SAO
11  USM00074917    35.117     -119.3 1941-12-01 11:00:00         SAO
12  USM00074917    35.117     -119.3 1941-12-01 12:00:00         SAO
13  USM00074917    35.117     -119.3 1941-12-01 13:00:00         SAO
14  USM00074917    35.117     -119.3 1941-12-01 14:00:00         SAO

    HourlyDewPointTemperature  HourlyDryBulbTemperature  HourlyPrecipitation  \
0                        11.9                      13.0                  0.0
1                        10.7                      12.4                  0.0
2                        11.3                      12.4                  0.0
3                        11.3                      12.4                  0.0
4                        11.9                      13.0                  0.0
5                        11.9                      13.0                  0.0
6                        11.9                      11.9                  0.0
7                        11.9                      11.9                  0.0
8                        11.9                      11.9                  0.0
9                        11.9                      11.9                  0.0
10                       12.4                      13.5                  0.0
11                       13.0                      15.7                  0.0
12                       12.4                      15.7                  0.0
13                       11.9                      18.0                  0.0
14                       11.9                      18.0                  0.0

    HourlyVisibility  HourlyWindDirection  HourlyWindSpeed  \
0               16.0                  0.0              0.0
1               16.0                158.0              0.5
2               16.0                  0.0              0.0
3               16.0                225.0              0.5
4               16.0                225.0              0.5
5               16.0                  0.0              0.0
6                0.2                 45.0              0.5
7                0.0                315.0              0.5
8                0.0                 90.0              0.5
9                0.2                  0.0              0.0
10               0.8                158.0              0.5
11               6.4                  0.0              0.0
12               8.0                  0.0              0.0
13               9.6                 90.0              1.0
14              12.8                360.0              1.5

    MonthlyNumberDaysWithHeavyFog  year  month  day  hour  minute
0                             NaN  1941     12    1     0       0
1                             NaN  1941     12    1     1       0
2                             NaN  1941     12    1     2       0
3                             NaN  1941     12    1     3       0
4                             NaN  1941     12    1     4       0
5                             NaN  1941     12    1     5       0
6                             NaN  1941     12    1     6       0
7                             NaN  1941     12    1     7       0
8                             NaN  1941     12    1     8       0
9                             NaN  1941     12    1     9       0
10                            NaN  1941     12    1    10       0
11                            NaN  1941     12    1    11       0
12                            NaN  1941     12    1    12       0
13                            NaN  1941     12    1    13       0
14                            NaN  1941     12    1    14       0

In [19]:
# # drop MonthlyNumberDaysWithHeavyFog column from CV_rows
# CV_data = CV_data.drop(columns=['MonthlyNumberDaysWithHeavyFog'])

CV_data.head()

,STATION,LATITUDE,LONGITUDE,DATE,REPORT_TYPE,HourlyDewPointTemperature,HourlyDryBulbTemperature,HourlyPrecipitation,HourlyVisibility,HourlyWindDirection,HourlyWindSpeed,MonthlyNumberDaysWithHeavyFog,year,month,day,hour,minute
0,USM00074917,35.117,-119.3,1941-12-01 00:00:00,SAO,11.9,13.0,0.0,16.0,0.0,0.0,NaN,1941,12,1,0,0
1,USM00074917,35.117,-119.3,1941-12-01 01:00:00,SAO,10.7,12.4,0.0,16.0,158.0,0.5,NaN,1941,12,1,1,0
2,USM00074917,35.117,-119.3,1941-12-01 02:00:00,SAO,11.3,12.4,0.0,16.0,0.0,0.0,NaN,1941,12,1,2,0
3,USM00074917,35.117,-119.3,1941-12-01 03:00:00,SAO,11.3,12.4,0.0,16.0,225.0,0.5,NaN,1941,12,1,3,0
4,USM00074917,35.117,-119.3,1941-12-01 04:00:00,SAO,11.9,13.0,0.0,16.0,225.0,0.5,NaN,1941,12,1,4,0

In [20]:
# read in station names CSV in order to change from station codes to station names
path = 'E:/Central Valley Fog/station_names.csv'
# path = '/Volumes/disk1/Central Valley Fog/station_names.csv'

station_names = pd.read_csv(path, low_memory = False)
# station_names = pd.read_csv(path, low_memory = False)


print(station_names)

     STATION_ID                                     STATION  BEGIN_DATE  \
0   USW00023155                              BAKERSFIELD AP  1927-12-31
1   USW00093216                                   BEALE AFB  1959-06-30
2   USI0000KC83                                       BYRON  2017-08-30
3   USL000CQUC1                                   CARQUINEZ  2016-02-23
4   USW00023203                                  CASTLE AFB  1941-12-31
5   USW00093203                    CHICO ARMY FLYING SCHOOL  1942-05-05
6   USW00023254                      CONCORD BUCHANAN FIELD  1968-12-31
7   USL000DPXC1                   DAVIS POINT SAN PABLO BAY  2011-09-09
8   USI0000KDLO                                 DELANO MUNI  2017-01-05
9   USW00053125                                      FRESNO  1892-12-31
10  USW00023167                 FRESNO CHANDLER DOWNTOWN AP  1933-04-30
11  USW00093193                        FRESNO YOSEMITE INTL  1941-12-03
12  USM00074917                                 GARDNER AAF  1941-11-30
13  USW00023106                                  HAMMER AAF  1942-01-01
14  USW00053119                        HANFORD MUNICIPAL AP  1998-02-18
15  USW00023110                          LEMOORE REEVES NAS  1961-06-30
16  USW00000205  LINCOLN REGIONAL AIRPORT KARL HARDER FIELD  2009-05-09
17  USW00023285                      LIVERMORE MUNICIPAL AP  1973-06-25
18  USW00023242                               LIVERMORE NAS  1945-01-31
19  USW00093242                         MADERA MUNICIPAL AP  1998-08-31
20  USL000MZXC1                             MARTINEZ-AMORCO  2011-09-09
21  USW00093205                   MARYSVILLE AIRPORT (ASOS)  1943-08-10
22  USW00093243                               MERCED 23 WSW  2004-03-25
23  USW00023257                         MERCED MUNICIPAL AP  1983-10-01
24  USW00023258                                  MODESTO AP  1906-02-28
25  USW00003183                                   MOJAVE AP  2005-05-24
26  USW00003129                                 MOJAVE MCAS  1955-10-03
27  USW00093108                                 MOJAVE MCAS  1945-03-31
28  USW00093227                         NAPA COUNTY AIRPORT  1972-12-31
29  USW00093210                       OROVILLE MUNICIPAL AP  1998-06-12
30  USL000PSBC1                      PITTSBURG (SUISUN BAY)  2011-09-09
31  USL000PCOC1                                PORT CHICAGO  2005-04-18
32  USW00023149               PORTERVILLE MUNICIPAL AIRPORT  2004-12-31
33  USW00024216                           RED BLUFF MUNI AP  1891-12-31
34  USW00024257                                  REDDING AP  1944-08-31
35  USI0000KO32                                REEDLEY MUNI  2018-04-03
36  USW00023271                            SACRAMENTO 5 ESE  1877-07-10
37  USW00023232                          SACRAMENTO AP ASOS  1930-12-31
38  USW00023206                       SACRAMENTO MATHER AFB  1929-12-31
39  USW00023208                    SACRAMENTO MCCLELLAN AFB  1939-11-08
40  USW00093225                  SACRAMENTO METROPOLITAN AP  1972-12-31
41  USL000SFXC1                   SAN FRANCISCO BAY RESERVE  2007-10-15
42  USM00074500                                SHERIDAN  CA  2002-02-26
43  USW00023237                                 STOCKTON AP  1941-01-03
44  USW00000479                 TEHACHAPI MUNICIPAL AIRPORT  1942-11-12
45  USI0000KTCY                                  TRACY MUNI  2018-09-23
46  USW00023202                            TRAVIS FIELD AFB  1943-08-10
47  USW00000174                          UNIVERSITY AIRPORT  2008-07-21
48  USL000UPBC1                          UP RAILROAD BRIDGE  2013-04-30
49  USW00093241                  VACAVILLE/NUT TREE AP ASOS  1998-04-05
50  USM00074918                          VERNALIS NAVAL AUX  1945-03-31
51  USW00093144                        VISALIA MUNICIPAL AP  1973-01-18
52  USW00023238                        WILLIAMS CAA AIRPORT  1947-12-31

      END_DATE STATE        COUNTRY   LATITUDE   LONGITUDE  ELEVATION
0   2026-06-20    CA  UNITED STATES  35.434240 -119.055240     489.84
1   2026-06-20    CA  UNITED STATES  39.133330 -121.433330        NaN
2   2026-06-20    CA  UNITED STATES  37.828400 -121.625833      76.00
3   2024-08-16    CA  UNITED STATES  38.066000 -122.230000       0.00
4   2026-06-19    CA  UNITED STATES  37.383330 -120.566670        NaN
5   2026-06-20    CA  UNITED STATES  39.800000 -121.850000     272.00
6   2026-06-30    CA  UNITED STATES  37.991650 -122.052680      23.03
7   2026-03-26    CA  UNITED STATES  38.057000 -122.259000      32.80
8   2026-06-20    CA  UNITED STATES  35.745581 -119.236503     314.00
9   1939-04-30    CA  UNITED STATES  36.733330 -119.800000        NaN
10  2026-06-20    CA  UNITED STATES  36.733330 -119.816670     276.00
11  2026-06-20    CA  UNITED STATES  36.779990 -119.720160     334.29
12  1945-02-20    CA  UNITED STATES  35.117000 -119.300000     436.40
13  1943-01-01    CA  UNITED STATES  36.766670 -119.700000        NaN
14  2026-06-20    CA  UNITED STATES  36.311400 -119.623190     249.21
15  2026-06-20    CA  UNITED STATES  36.333330 -119.950000        NaN
16  2026-06-20    CA  UNITED STATES  38.909000 -121.351000     122.00
17  2026-06-30    CA  UNITED STATES  37.693090 -121.814900     392.88
18  1946-08-10    CA  UNITED STATES  37.683330 -121.700000        NaN
19  2026-06-20    CA  UNITED STATES  36.985050 -120.110680     251.31
20  2026-03-26    CA  UNITED STATES  38.033000 -122.125000      32.80
21  2026-06-20    CA  UNITED STATES  39.102050 -121.568840      61.98
22  2026-01-11    CA  UNITED STATES  37.238100 -120.882500      78.00
23  2026-06-20    CA  UNITED STATES  37.285970 -120.517880     152.45
24  2026-06-20    CA  UNITED STATES  37.625440 -120.954920      87.09
25  2026-06-20    CA  UNITED STATES  35.066670 -118.150000    2787.00
26  1958-09-30    CA  UNITED STATES  35.050000 -118.166670        NaN
27  1946-12-31    CA  UNITED STATES  35.116670 -118.150000        NaN
28  2026-06-30    CA  UNITED STATES  38.207500 -122.280410      15.56
29  2026-06-20    CA  UNITED STATES  39.494300 -121.622260     186.54
30  2026-03-26    CA  UNITED STATES  38.042000 -121.887000      32.80
31  2026-03-26    CA  UNITED STATES  38.057000 -122.038000       6.60
32  2026-06-20    CA  UNITED STATES  36.029440 -119.062500        NaN
33  2026-06-20    CA  UNITED STATES  40.151860 -122.254780     354.49
34  2026-06-20    CA  UNITED STATES  40.514620 -122.297730     500.77
35  2026-06-20    CA  UNITED STATES  36.666340 -119.449847     383.00
36  2025-05-31    CA  UNITED STATES  38.555200 -121.418300      38.00
37  2026-06-20    CA  UNITED STATES  38.506590 -121.496040      19.32
38  2026-06-20    CA  UNITED STATES  38.566670 -121.300000        NaN
39  2026-06-20    CA  UNITED STATES  38.666670 -121.400000        NaN
40  2026-06-20    CA  UNITED STATES  38.700690 -121.594790      24.49
41  2026-03-26    CA  UNITED STATES  38.216667 -122.016667       9.80
42  2002-02-26   NaN  UNITED STATES  39.000000 -121.333333     196.90
43  2026-06-20    CA  UNITED STATES  37.889970 -121.226370      27.10
44  2026-06-20    CA  UNITED STATES  35.134900 -118.439300    4001.00
45  2026-06-19    CA  UNITED STATES  37.688956 -121.441539     193.00
46  2026-06-20    CA  UNITED STATES  38.266670 -121.933330        NaN
47  2026-06-20    CA  UNITED STATES  38.533000 -121.783000      69.00
48  2026-03-26    CA  UNITED STATES  38.038000 -122.121000       9.80
49  2026-06-20    CA  UNITED STATES  38.377530 -121.958540     104.10
50  1946-01-15    CA  UNITED STATES  37.600000 -121.300000     193.60
51  2026-06-20    CA  UNITED STATES  36.316670 -119.400000        NaN
52  1952-12-31    CA  UNITED STATES  39.100000 -122.150000     128.00

In [21]:
# change station ID to station name in CV_rows
station_id_to_name = station_names.set_index('STATION_ID')['STATION']

CV_data = CV_data.rename(columns={'STATION': 'STATION_ID'})
CV_data['STATION'] = CV_data['STATION_ID'].map(station_id_to_name).fillna(CV_data['STATION_ID'])

# check:
print(CV_data[['STATION_ID', 'STATION']].head())

    STATION_ID      STATION
0  USM00074917  GARDNER AAF
1  USM00074917  GARDNER AAF
2  USM00074917  GARDNER AAF
3  USM00074917  GARDNER AAF
4  USM00074917  GARDNER AAF

In [22]:

stations_to_keep = [
    "BAKERSFIELD AP",
    "BEALE AFB",
    "CASTLE AFB",
    "FRESNO YOSEMITE INTL",
    "LEMOORE REEVES NAS",
    "LIVERMORE MUNICIPAL AP",
    "RED BLUFF MUNI AP",
    "REDDING AP",
    "SACRAMENTO AP ASOS",
    "SACRAMENTO MCCLELLAN AFB",
    "SACRAMENTO MATHER AFB",
    "SACRAMENTO METROPOLITAN AP",
    "STOCKTON AP",
    "TRAVIS FIELD AFB",
]

CV_data = CV_data[CV_data["STATION"].isin(stations_to_keep)].copy()

print(CV_data["STATION"].value_counts())

STATION
SACRAMENTO AP ASOS            921060
SACRAMENTO MCCLELLAN AFB      914064
BAKERSFIELD AP                892809
TRAVIS FIELD AFB              889607
FRESNO YOSEMITE INTL          834929
RED BLUFF MUNI AP             826407
SACRAMENTO MATHER AFB         783597
STOCKTON AP                   776669
CASTLE AFB                    695055
BEALE AFB                     689860
LEMOORE REEVES NAS            660998
REDDING AP                    527262
SACRAMENTO METROPOLITAN AP    489340
LIVERMORE MUNICIPAL AP        407422
Name: count, dtype: int64

In [23]:
CV_data[CV_data["HourlyVisibility"] > 17]

Empty DataFrame
Columns: [STATION_ID, LATITUDE, LONGITUDE, DATE, REPORT_TYPE, HourlyDewPointTemperature, HourlyDryBulbTemperature, HourlyPrecipitation, HourlyVisibility, HourlyWindDirection, HourlyWindSpeed, MonthlyNumberDaysWithHeavyFog, year, month, day, hour, minute, STATION]
Index: []

In [24]:
CV_data = CV_data[CV_data["HourlyVisibility"] < 17.000]

In [25]:
# save cleaned dataframe
CV_data.to_csv('CV_station_rows_nonna.csv', index=False)