In [1]:
# importing needed packages
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#read in Central Valley csvs from external drive
#path1 = '/Volumes/disk1/Central Valley Fog/4205333.csv'
#path2 = '/Volumes/disk1/Central Valley Fog/4206426.csv'
#path3 = '/Volumes/disk1/Central Valley Fog/4206427.csv'
#path1 = 'E:/Central Valley Fog/4205333.csv'
#path2 = 'E:/Central Valley Fog/4206426.csv'
#path3 = 'E:/Central Valley Fog/4206427.csv'

path1 = 'E:/Central Valley Fog/4341535.csv'
path2 = 'E:/Central Valley Fog/4341537.csv'

In [3]:
# create dataframes with only the columns we need
# units: HourlyVisibility: km to thousandths, HourlyPrecipitation: mm to tenths
df1 = pd.read_csv(path1, usecols=['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'HourlyVisibility','HourlyPrecipitation','MonthlyNumberDaysWithHeavyFog'],low_memory=False)
df2 = pd.read_csv(path2, usecols=['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'HourlyVisibility','HourlyPrecipitation','MonthlyNumberDaysWithHeavyFog'],low_memory=False)
#df3 = pd.read_csv(path3, usecols=['STATION', 'DATE', 'LATITUDE', 'LONGITUDE', 'HourlyVisibility','HourlyPrecipitation','MonthlyNumberDaysWithHeavyFog'],low_memory=False)

In [4]:
#check
df1.head()

,STATION,LATITUDE,LONGITUDE,DATE,HourlyPrecipitation,HourlyVisibility,MonthlyNumberDaysWithHeavyFog
0,USM00074917,35.117,-119.3,1941-12-01T00:00:00,NaN,160.000,NaN
1,USM00074917,35.117,-119.3,1941-12-01T01:00:00,NaN,160.000,NaN
2,USM00074917,35.117,-119.3,1941-12-01T02:00:00,NaN,160.000,NaN
3,USM00074917,35.117,-119.3,1941-12-01T03:00:00,NaN,160.000,NaN
4,USM00074917,35.117,-119.3,1941-12-01T04:00:00,NaN,160.000,NaN

In [5]:
# print all column names
for col in df1.columns:
    print(col)

STATION
LATITUDE
LONGITUDE
DATE
HourlyPrecipitation
HourlyVisibility
MonthlyNumberDaysWithHeavyFog

In [6]:
#df_list = [df1, df2, df3] 
df_list = [df1, df2] 

CV_data = pd.concat(df_list, ignore_index = True)

print(CV_data.head(15))

        STATION  LATITUDE  LONGITUDE                 DATE HourlyPrecipitation  \
0   USM00074917    35.117     -119.3  1941-12-01T00:00:00                 NaN
1   USM00074917    35.117     -119.3  1941-12-01T01:00:00                 NaN
2   USM00074917    35.117     -119.3  1941-12-01T02:00:00                 NaN
3   USM00074917    35.117     -119.3  1941-12-01T03:00:00                 NaN
4   USM00074917    35.117     -119.3  1941-12-01T04:00:00                 NaN
5   USM00074917    35.117     -119.3  1941-12-01T05:00:00                 NaN
6   USM00074917    35.117     -119.3  1941-12-01T06:00:00                 NaN
7   USM00074917    35.117     -119.3  1941-12-01T07:00:00                 NaN
8   USM00074917    35.117     -119.3  1941-12-01T08:00:00                 NaN
9   USM00074917    35.117     -119.3  1941-12-01T09:00:00                 NaN
10  USM00074917    35.117     -119.3  1941-12-01T10:00:00                 NaN
11  USM00074917    35.117     -119.3  1941-12-01T11:00:00                 NaN
12  USM00074917    35.117     -119.3  1941-12-01T12:00:00                 NaN
13  USM00074917    35.117     -119.3  1941-12-01T13:00:00                 NaN
14  USM00074917    35.117     -119.3  1941-12-01T14:00:00                 NaN

   HourlyVisibility  MonthlyNumberDaysWithHeavyFog
0           160.000                            NaN
1           160.000                            NaN
2           160.000                            NaN
3           160.000                            NaN
4           160.000                            NaN
5           160.000                            NaN
6             0.200                            NaN
7             0.000                            NaN
8             0.000                            NaN
9             0.200                            NaN
10            0.800                            NaN
11            6.400                            NaN
12            8.000                            NaN
13            9.600                            NaN
14           12.800                            NaN

In [7]:
# filter for rows that have hourly visibility data
CV_rows = CV_data[CV_data['HourlyVisibility'].notna()]
print(CV_rows)

              STATION  LATITUDE  LONGITUDE                 DATE  \
0         USM00074917   35.1170  -119.3000  1941-12-01T00:00:00
1         USM00074917   35.1170  -119.3000  1941-12-01T01:00:00
2         USM00074917   35.1170  -119.3000  1941-12-01T02:00:00
3         USM00074917   35.1170  -119.3000  1941-12-01T03:00:00
4         USM00074917   35.1170  -119.3000  1941-12-01T04:00:00
...               ...       ...        ...                  ...
14495830  USW00024257   40.5175  -122.2986  2026-06-20T04:53:00
14495831  USW00024257   40.5175  -122.2986  2026-06-20T05:53:00
14495832  USW00024257   40.5175  -122.2986  2026-06-20T06:53:00
14495833  USW00024257   40.5175  -122.2986  2026-06-20T07:53:00
14495834  USW00024257   40.5175  -122.2986  2026-06-20T08:53:00

         HourlyPrecipitation HourlyVisibility  MonthlyNumberDaysWithHeavyFog
0                        NaN          160.000                            NaN
1                        NaN          160.000                            NaN
2                        NaN          160.000                            NaN
3                        NaN          160.000                            NaN
4                        NaN          160.000                            NaN
...                      ...              ...                            ...
14495830                 NaN           16.090                            NaN
14495831                 NaN           16.090                            NaN
14495832                 NaN           16.090                            NaN
14495833                 NaN           16.090                            NaN
14495834                 NaN           16.090                            NaN

[10821802 rows x 7 columns]

In [8]:
#fill in missing values for HourlyPrecipitation with 0
CV_rows["HourlyPrecipitation"] = CV_rows["HourlyPrecipitation"].fillna(0)

In [9]:
# convert date column to datetime format
CV_rows["DATE"] = pd.to_datetime(CV_rows["DATE"])

In [10]:
# extract year and month from date column and add as new columns
CV_rows["year"] = CV_rows["DATE"].dt.year
CV_rows["month"] = CV_rows["DATE"].dt.month
CV_rows["day"] = CV_rows["DATE"].dt.day
CV_rows["hour"] = CV_rows["DATE"].dt.hour
CV_rows["minute"] = CV_rows["DATE"].dt.minute
print(CV_rows.head(15))

        STATION  LATITUDE  LONGITUDE                DATE HourlyPrecipitation  \
0   USM00074917    35.117     -119.3 1941-12-01 00:00:00                   0
1   USM00074917    35.117     -119.3 1941-12-01 01:00:00                   0
2   USM00074917    35.117     -119.3 1941-12-01 02:00:00                   0
3   USM00074917    35.117     -119.3 1941-12-01 03:00:00                   0
4   USM00074917    35.117     -119.3 1941-12-01 04:00:00                   0
5   USM00074917    35.117     -119.3 1941-12-01 05:00:00                   0
6   USM00074917    35.117     -119.3 1941-12-01 06:00:00                   0
7   USM00074917    35.117     -119.3 1941-12-01 07:00:00                   0
8   USM00074917    35.117     -119.3 1941-12-01 08:00:00                   0
9   USM00074917    35.117     -119.3 1941-12-01 09:00:00                   0
10  USM00074917    35.117     -119.3 1941-12-01 10:00:00                   0
11  USM00074917    35.117     -119.3 1941-12-01 11:00:00                   0
12  USM00074917    35.117     -119.3 1941-12-01 12:00:00                   0
13  USM00074917    35.117     -119.3 1941-12-01 13:00:00                   0
14  USM00074917    35.117     -119.3 1941-12-01 14:00:00                   0

   HourlyVisibility  MonthlyNumberDaysWithHeavyFog  year  month  day  hour  \
0           160.000                            NaN  1941     12    1     0
1           160.000                            NaN  1941     12    1     1
2           160.000                            NaN  1941     12    1     2
3           160.000                            NaN  1941     12    1     3
4           160.000                            NaN  1941     12    1     4
5           160.000                            NaN  1941     12    1     5
6             0.200                            NaN  1941     12    1     6
7             0.000                            NaN  1941     12    1     7
8             0.000                            NaN  1941     12    1     8
9             0.200                            NaN  1941     12    1     9
10            0.800                            NaN  1941     12    1    10
11            6.400                            NaN  1941     12    1    11
12            8.000                            NaN  1941     12    1    12
13            9.600                            NaN  1941     12    1    13
14           12.800                            NaN  1941     12    1    14

    minute
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0

In [11]:
# convert hourly precipitation and visibility to numeric values
CV_rows["HourlyPrecipitation"] = pd.to_numeric(CV_rows["HourlyPrecipitation"], errors='coerce')
CV_rows["HourlyVisibility"] = pd.to_numeric(CV_rows["HourlyVisibility"], errors='coerce')

In [12]:
# drop MonthlyNumberDaysWithHeavyFog column from CV_rows
CV_rows = CV_rows.drop(columns=['MonthlyNumberDaysWithHeavyFog'])

CV_rows.head()

,STATION,LATITUDE,LONGITUDE,DATE,HourlyPrecipitation,HourlyVisibility,year,month,day,hour,minute
0,USM00074917,35.117,-119.3,1941-12-01 00:00:00,0.0,160.0,1941,12,1,0,0
1,USM00074917,35.117,-119.3,1941-12-01 01:00:00,0.0,160.0,1941,12,1,1,0
2,USM00074917,35.117,-119.3,1941-12-01 02:00:00,0.0,160.0,1941,12,1,2,0
3,USM00074917,35.117,-119.3,1941-12-01 03:00:00,0.0,160.0,1941,12,1,3,0
4,USM00074917,35.117,-119.3,1941-12-01 04:00:00,0.0,160.0,1941,12,1,4,0

In [13]:
# save cleaned dataframe
CV_rows.to_csv('CV_rows_cleaned.csv', index=False)

In [14]:
fog_rows = CV_data[CV_data["MonthlyNumberDaysWithHeavyFog"].notna()]
print(fog_rows)

              STATION  LATITUDE  LONGITUDE                 DATE  \
729413    USW00053119  36.31889 -119.62889  2006-01-31T23:59:00
730424    USW00053119  36.31889 -119.62889  2006-02-28T23:59:00
731401    USW00053119  36.31889 -119.62889  2006-03-31T23:59:00
732297    USW00053119  36.31889 -119.62889  2006-04-30T23:59:00
736987    USW00053119  36.31889 -119.62889  2006-10-31T23:59:00
...               ...       ...        ...                  ...
14475387  USW00024257  40.51750 -122.29860  2024-11-30T23:59:00
14479028  USW00024257  40.51750 -122.29860  2025-02-28T23:59:00
14480252  USW00024257  40.51750 -122.29860  2025-03-31T23:59:00
14491555  USW00024257  40.51750 -122.29860  2026-01-31T23:59:00
14492658  USW00024257  40.51750 -122.29860  2026-02-28T23:59:00

         HourlyPrecipitation HourlyVisibility  MonthlyNumberDaysWithHeavyFog
729413                   NaN              NaN                           19.0
730424                   NaN              NaN                           16.0
731401                   NaN              NaN                            6.0
732297                   NaN              NaN                            1.0
736987                   NaN              NaN                            1.0
...                      ...              ...                            ...
14475387                 NaN              NaN                            1.0
14479028                 NaN              NaN                            2.0
14480252                 NaN              NaN                            2.0
14491555                 NaN              NaN                            5.0
14492658                 NaN              NaN                            2.0

[2485 rows x 7 columns]

In [15]:
fog_rows["MonthlyNumberDaysWithHeavyFog"] = pd.to_numeric(fog_rows["MonthlyNumberDaysWithHeavyFog"], errors='coerce')

In [16]:
fog_rows.to_csv('fog_rows_cleaned.csv', index=False)