In [1]:
# importing needed packages
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
#read in Central Valley csvs from external drive
#path1 = '/Volumes/disk1/Central Valley Fog/4205333.csv'
#path2 = '/Volumes/disk1/Central Valley Fog/4206426.csv'
#path3 = '/Volumes/disk1/Central Valley Fog/4206427.csv'
#path1 = 'E:/Central Valley Fog/4205333.csv'
#path2 = 'E:/Central Valley Fog/4206426.csv'
#path3 = 'E:/Central Valley Fog/4206427.csv'

# path1 = 'E:/Central Valley Fog/Sac data/4341535.csv'
# path2 = 'E:/Central Valley Fog/Sac data/4341537.csv'
# path1 = '/Volumes/DISK1/Central Valley Fog/Sac data/4341535.csv'
# path2 = '/Volumes/DISK1/Central Valley Fog/Sac data/4341537.csv'

# path1 = '/Volumes/DISK1/Central Valley Fog/Raw data/GHCNh_USW00023232_por.psv'
# path2 = '/Volumes/DISK1/Central Valley Fog/Raw data/GHCNh_USW00023232_por.psv'
path = 'E:\\GHCN files'
# path1 = 'e:\\Central Valley Fog\\Raw data\\GHCNh_USW00023232_por.psv'
# path2 = 'e:\\Central Valley Fog\\Raw data\\GHCNh_USW00023232_por.psv'

In [3]:
#for each file in the folder path, print the column names
for filename in os.listdir(path):
    if filename.endswith(".psv"):
        full_path = os.path.join(path, filename)
        df = pd.read_csv(full_path, nrows=0, sep='|', low_memory=False)
        print(f"{full_path}:")
        print(df.columns.tolist())
        print()

E:\GHCN files\GHCNh_USW00023155_por.psv:
['STATION', 'Station_name', 'DATE', 'Year', 'Month', 'Day', 'Hour', 'Minute', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'temperature', 'temperature_Measurement_Code', 'temperature_Quality_Code', 'temperature_Report_Type', 'temperature_Source_Code', 'temperature_Source_Station_ID', 'dew_point_temperature', 'dew_point_temperature_Measurement_Code', 'dew_point_temperature_Quality_Code', 'dew_point_temperature_Report_Type', 'dew_point_temperature_Source_Code', 'dew_point_temperature_Source_Station_ID', 'station_level_pressure', 'station_level_pressure_Measurement_Code', 'station_level_pressure_Quality_Code', 'station_level_pressure_Report_Type', 'station_level_pressure_Source_Code', 'station_level_pressure_Source_Station_ID', 'sea_level_pressure', 'sea_level_pressure_Measurement_Code', 'sea_level_pressure_Quality_Code', 'sea_level_pressure_Report_Type', 'sea_level_pressure_Source_Code', 'sea_level_pressure_Source_Station_ID', 'wind_direction', 'wind_direction_Measurement_Code', 'wind_direction_Quality_Code', 'wind_direction_Report_Type', 'wind_direction_Source_Code', 'wind_direction_Source_Station_ID', 'wind_speed', 'wind_speed_Measurement_Code', 'wind_speed_Quality_Code', 'wind_speed_Report_Type', 'wind_speed_Source_Code', 'wind_speed_Source_Station_ID', 'wind_gust', 'wind_gust_Measurement_Code', 'wind_gust_Quality_Code', 'wind_gust_Report_Type', 'wind_gust_Source_Code', 'wind_gust_Source_Station_ID', 'precipitation', 'precipitation_Measurement_Code', 'precipitation_Quality_Code', 'precipitation_Report_Type', 'precipitation_Source_Code', 'precipitation_Source_Station_ID', 'relative_humidity', 'relative_humidity_Measurement_Code', 'relative_humidity_Quality_Code', 'relative_humidity_Report_Type', 'relative_humidity_Source_Code', 'relative_humidity_Source_Station_ID', 'wet_bulb_temperature', 'wet_bulb_temperature_Measurement_Code', 'wet_bulb_temperature_Quality_Code', 'wet_bulb_temperature_Report_Type', 'wet_bulb_temperature_Source_Code', 'wet_bulb_temperature_Source_Station_ID', 'pres_wx_MW1', 'pres_wx_MW1_Measurement_Code', 'pres_wx_MW1_Quality_Code', 'pres_wx_MW1_Report_Type', 'pres_wx_MW1_Source_Code', 'pres_wx_MW1_Source_Station_ID', 'pres_wx_MW2', 'pres_wx_MW2_Measurement_Code', 'pres_wx_MW2_Quality_Code', 'pres_wx_MW2_Report_Type', 'pres_wx_MW2_Source_Code', 'pres_wx_MW2_Source_Station_ID', 'pres_wx_MW3', 'pres_wx_MW3_Measurement_Code', 'pres_wx_MW3_Quality_Code', 'pres_wx_MW3_Report_Type', 'pres_wx_MW3_Source_Code', 'pres_wx_MW3_Source_Station_ID', 'pres_wx_AU1', 'pres_wx_AU1_Measurement_Code', 'pres_wx_AU1_Quality_Code', 'pres_wx_AU1_Report_Type', 'pres_wx_AU1_Source_Code', 'pres_wx_AU1_Source_Station_ID', 'pres_wx_AU2', 'pres_wx_AU2_Measurement_Code', 'pres_wx_AU2_Quality_Code', 'pres_wx_AU2_Report_Type', 'pres_wx_AU2_Source_Code', 'pres_wx_AU2_Source_Station_ID', 'pres_wx_AU3', 'pres_wx_AU3_Measurement_Code', 'pres_wx_AU3_Quality_Code', 'pres_wx_AU3_Report_Type', 'pres_wx_AU3_Source_Code', 'pres_wx_AU3_Source_Station_ID', 'pres_wx_AW1', 'pres_wx_AW1_Measurement_Code', 'pres_wx_AW1_Quality_Code', 'pres_wx_AW1_Report_Type', 'pres_wx_AW1_Source_Code', 'pres_wx_AW1_Source_Station_ID', 'pres_wx_AW2', 'pres_wx_AW2_Measurement_Code', 'pres_wx_AW2_Quality_Code', 'pres_wx_AW2_Report_Type', 'pres_wx_AW2_Source_Code', 'pres_wx_AW2_Source_Station_ID', 'pres_wx_AW3', 'pres_wx_AW3_Measurement_Code', 'pres_wx_AW3_Quality_Code', 'pres_wx_AW3_Report_Type', 'pres_wx_AW3_Source_Code', 'pres_wx_AW3_Source_Station_ID', 'snow_depth', 'snow_depth_Measurement_Code', 'snow_depth_Quality_Code', 'snow_depth_Report_Type', 'snow_depth_Source_Code', 'snow_depth_Source_Station_ID', 'visibility', 'visibility_Measurement_Code', 'visibility_Quality_Code', 'visibility_Report_Type', 'visibility_Source_Code', 'visibility_Source_Station_ID', 'altimeter', 'altimeter_Measurement_Code', 'altimeter_Quality_Code', 'altimeter_Report_Type', 'altimeter_Source_Code', 'altimeter_Source_Station_ID', 'pressure_3hr_change', 'pressure_3hr_change_Measurement_Code', 'pressure_3hr_change_Quality_Code', 'pressure_3hr_change_Report_Type', 'pressure_3hr_change_Source_Code', 'pressure_3hr_change_Source_Station_ID', 'sky_condition', 'sky_condition_Measurement_Code', 'sky_condition_Quality_Code', 'sky_condition_Report_Type', 'sky_condition_Source_Code', 'sky_condition_Source_Station_ID', 'sky_condition_baseht', 'sky_condition_baseht_Measurement_Code', 'sky_condition_baseht_Quality_Code', 'sky_condition_baseht_Report_Type', 'sky_condition_baseht_Source_Code', 'sky_condition_baseht_Source_Station_ID', 'ceiling_height', 'ceiling_height_Measurement_Code', 'ceiling_height_Quality_Code', 'ceiling_height_Report_Type', 'ceiling_height_Source_Code', 'ceiling_height_Source_Station_ID', 'sky_cover_layer_1', 'sky_cover_layer_1_Measurement_Code', 'sky_cover_layer_1_Quality_Code', 'sky_cover_layer_1_Report_Type', 'sky_cover_layer_1_Source_Code', 'sky_cover_layer_1_Source_Station_ID', 'sky_cover_layer_2', 'sky_cover_layer_2_Measurement_Code', 'sky_cover_layer_2_Quality_Code', 'sky_cover_layer_2_Report_Type', 'sky_cover_layer_2_Source_Code', 'sky_cover_layer_2_Source_Station_ID', 'sky_cover_layer_3', 'sky_cover_layer_3_Measurement_Code', 'sky_cover_layer_3_Quality_Code', 'sky_cover_layer_3_Report_Type', 'sky_cover_layer_3_Source_Code', 'sky_cover_layer_3_Source_Station_ID', 'sky_cover_layer_4', 'sky_cover_layer_4_Measurement_Code', 'sky_cover_layer_4_Quality_Code', 'sky_cover_layer_4_Report_Type', 'sky_cover_layer_4_Source_Code', 'sky_cover_layer_4_Source_Station_ID', 'sky_cover_layer_baseht_1', 'sky_cover_layer_baseht_1_Measurement_Code', 'sky_cover_layer_baseht_1_Quality_Code', 'sky_cover_layer_baseht_1_Report_Type', 'sky_cover_layer_baseht_1_Source_Code', 'sky_cover_layer_baseht_1_Source_Station_ID', 'sky_cover_layer_baseht_2', 'sky_cover_layer_baseht_2_Measurement_Code', 'sky_cover_layer_baseht_2_Quality_Code', 'sky_cover_layer_baseht_2_Report_Type', 'sky_cover_layer_baseht_2_Source_Code', 'sky_cover_layer_baseht_2_Source_Station_ID', 'sky_cover_layer_baseht_3', 'sky_cover_layer_baseht_3_Measurement_Code', 'sky_cover_layer_baseht_3_Quality_Code', 'sky_cover_layer_baseht_3_Report_Type', 'sky_cover_layer_baseht_3_Source_Code', 'sky_cover_layer_baseht_3_Source_Station_ID', 'sky_cover_layer_baseht_4', 'sky_cover_layer_baseht_4_Measurement_Code', 'sky_cover_layer_baseht_4_Quality_Code', 'sky_cover_layer_baseht_4_Report_Type', 'sky_cover_layer_baseht_4_Source_Code', 'sky_cover_layer_baseht_4_Source_Station_ID', 'sky_cover_summation_1', 'sky_cover_summation_1_Measurement_Code', 'sky_cover_summation_1_Quality_Code', 'sky_cover_summation_1_Report_Type', 'sky_cover_summation_1_Source_Code', 'sky_cover_summation_1_Source_Station_ID', 'sky_cover_summation_2', 'sky_cover_summation_2_Measurement_Code', 'sky_cover_summation_2_Quality_Code', 'sky_cover_summation_2_Report_Type', 'sky_cover_summation_2_Source_Code', 'sky_cover_summation_2_Source_Station_ID', 'sky_cover_summation_3', 'sky_cover_summation_3_Measurement_Code', 'sky_cover_summation_3_Quality_Code', 'sky_cover_summation_3_Report_Type', 'sky_cover_summation_3_Source_Code', 'sky_cover_summation_3_Source_Station_ID', 'sky_cover_summation_4', 'sky_cover_summation_4_Measurement_Code', 'sky_cover_summation_4_Quality_Code', 'sky_cover_summation_4_Report_Type', 'sky_cover_summation_4_Source_Code', 'sky_cover_summation_4_Source_Station_ID', 'sky_cover_summation_baseht_1', 'sky_cover_summation_baseht_1_Measurement_Code', 'sky_cover_summation_baseht_1_Quality_Code', 'sky_cover_summation_baseht_1_Report_Type', 'sky_cover_summation_baseht_1_Source_Code', 'sky_cover_summation_baseht_1_Source_Station_ID', 'sky_cover_summation_baseht_2', 'sky_cover_summation_baseht_2_Measurement_Code', 'sky_cover_summation_baseht_2_Quality_Code', 'sky_cover_summation_baseht_2_Report_Type', 'sky_cover_summation_baseht_2_Source_Code', 'sky_cover_summation_baseht_2_Source_Station_ID', 'sky_cover_summation_baseht_3', 'sky_cover_summation_baseht_3_Measurement_Code', 'sky_cover_summation_baseht_3_Quality_Code', 'sky_cover_summation_baseht_3_Report_Type', 'sky_cover_summation_baseht_3_Source_Code', 'sky_cover_summation_baseht_3_Source_Station_ID', 'sky_cover_summation_baseht_4', 'sky_cover_summation_baseht_4_Measurement_Code', 'sky_cover_summation_baseht_4_Quality_Code', 'sky_cover_summation_baseht_4_Report_Type', 'sky_cover_summation_baseht_4_Source_Code', 'sky_cover_summation_baseht_4_Source_Station_ID', 'precipitation_5_minute', 'precipitation_5_minute_Measurement_Code', 'precipitation_5_minute_Quality_Code', 'precipitation_5_minute_Report_Type', 'precipitation_5_minute_Source_Code', 'precipitation_5_minute_Source_Station_ID', 'precipitation_15_minute', 'precipitation_15_minute_Measurement_Code', 'precipitation_15_minute_Quality_Code', 'precipitation_15_minute_Report_Type', 'precipitation_15_minute_Source_Code', 'precipitation_15_minute_Source_Station_ID', 'precipitation_3_hour', 'precipitation_3_hour_Measurement_Code', 'precipitation_3_hour_Quality_Code', 'precipitation_3_hour_Report_Type', 'precipitation_3_hour_Source_Code', 'precipitation_3_hour_Source_Station_ID', 'precipitation_6_hour', 'precipitation_6_hour_Measurement_Code', 'precipitation_6_hour_Quality_Code', 'precipitation_6_hour_Report_Type', 'precipitation_6_hour_Source_Code', 'precipitation_6_hour_Source_Station_ID', 'precipitation_9_hour', 'precipitation_9_hour_Measurement_Code', 'precipitation_9_hour_Quality_Code', 'precipitation_9_hour_Report_Type', 'precipitation_9_hour_Source_Code', 'precipitation_9_hour_Source_Station_ID', 'precipitation_12_hour', 'precipitation_12_hour_Measurement_Code', 'precipitation_12_hour_Quality_Code', 'precipitation_12_hour_Report_Type', 'precipitation_12_hour_Source_Code', 'precipitation_12_hour_Source_Station_ID', 'precipitation_15_hour', 'precipitation_15_hour_Measurement_Code', 'precipitation_15_hour_Quality_Code', 'precipitation_15_hour_Report_Type', 'precipitation_15_hour_Source_Code', 'precipitation_15_hour_Source_Station_ID', 'precipitation_18_hour', 'precipitation_18_hour_Measurement_Code', 'precipitation_18_hour_Quality_Code', 'precipitation_18_hour_Report_Type', 'precipitation_18_hour_Source_Code', 'precipitation_18_hour_Source_Station_ID', 'precipitation_21_hour', 'precipitation_21_hour_Measurement_Code', 'precipitation_21_hour_Quality_Code', 'precipitation_21_hour_Report_Type', 'precipitation_21_hour_Source_Code', 'precipitation_21_hour_Source_Station_ID', 'precipitation_24_hour', 'precipitation_24_hour_Measurement_Code', 'precipitation_24_hour_Quality_Code', 'precipitation_24_hour_Report_Type', 'precipitation_24_hour_Source_Code', 'precipitation_24_hour_Source_Station_ID', 'REM', 'REM_Measurement_Code', 'REM_Quality_Code', 'REM_Report_Type', 'REM_Source_Code', 'REM_Source_Station_ID']

E:\GHCN files\GHCNh_USW00093216_por.psv:

In [4]:
cols = ['STATION', 'Station_name', 'DATE', 'Year', 'Month', 'Day', 'Hour', 'Minute', 'LATITUDE', 'LONGITUDE','temperature','dew_point_temperature','wind_direction','wind_speed','precipitation', 'visibility']

dfs = {}
for filename in os.listdir(path):
    if filename.endswith(".psv"):
        full_path = os.path.join(path, filename)
        dfs[filename] = pd.read_csv(full_path, sep='|', usecols=cols, low_memory=False)
        print(f"{filename}: {dfs[filename].shape}")

GHCNh_USW00023155_por.psv: (981526, 16)
GHCNh_USW00093216_por.psv: (687629, 16)
GHCNh_USW00023203_por.psv: (687737, 16)
GHCNh_USW00093203_por.psv: (473664, 16)
GHCNh_USW00023254_por.psv: (496520, 16)
GHCNh_USW00023167_por.psv: (315783, 16)
GHCNh_USW00093193_por.psv: (867287, 16)
GHCNh_USW00023110_por.psv: (684213, 16)
GHCNh_USW00023285_por.psv: (460148, 16)
GHCNh_USW00093205_por.psv: (518905, 16)
GHCNh_USW00023257_por.psv: (393033, 16)
GHCNh_USW00023258_por.psv: (488230, 16)
GHCNh_USW00093227_por.psv: (484811, 16)
GHCNh_USW00024216_por.psv: (838197, 16)
GHCNh_USW00024257_por.psv: (573751, 16)
GHCNh_USW00023271_por.psv: (60704, 16)
GHCNh_USW00023232_por.psv: (946610, 16)
GHCNh_USW00023206_por.psv: (781906, 16)
GHCNh_USW00023208_por.psv: (911950, 16)
GHCNh_USW00093225_por.psv: (481267, 16)
GHCNh_USW00023237_por.psv: (805800, 16)
GHCNh_USW00000479_por.psv: (439768, 16)
GHCNh_USW00023202_por.psv: (883401, 16)
GHCNh_USW00093144_por.psv: (630457, 16)

In [5]:
# concatenate the dataframes into one
all_data = pd.concat(dfs.values(), ignore_index=True)
print(f"Combined dataframe shape: {all_data.shape}")
all_data.head()
all_data.info()

Combined dataframe shape: (14893297, 16)
<class 'pandas.DataFrame'>
RangeIndex: 14893297 entries, 0 to 14893296
Data columns (total 16 columns):
 #   Column                 Dtype
---  ------                 -----
 0   STATION                str
 1   Station_name           str
 2   DATE                   str
 3   Year                   int64
 4   Month                  int64
 5   Day                    int64
 6   Hour                   int64
 7   Minute                 int64
 8   LATITUDE               float64
 9   LONGITUDE              float64
 10  temperature            float64
 11  dew_point_temperature  float64
 12  wind_direction         float64
 13  wind_speed             float64
 14  precipitation          float64
 15  visibility             float64
dtypes: float64(8), int64(5), str(3)
memory usage: 1.8 GB

In [6]:
#convert date to datetime
all_data['DATE'] = pd.to_datetime(all_data['DATE'], errors='coerce')
all_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 14893297 entries, 0 to 14893296
Data columns (total 16 columns):
 #   Column                 Dtype
---  ------                 -----
 0   STATION                str
 1   Station_name           str
 2   DATE                   datetime64[us]
 3   Year                   int64
 4   Month                  int64
 5   Day                    int64
 6   Hour                   int64
 7   Minute                 int64
 8   LATITUDE               float64
 9   LONGITUDE              float64
 10  temperature            float64
 11  dew_point_temperature  float64
 12  wind_direction         float64
 13  wind_speed             float64
 14  precipitation          float64
 15  visibility             float64
dtypes: datetime64[us](1), float64(8), int64(5), str(2)
memory usage: 1.8 GB

In [7]:
# Rename columns
all_data.rename(columns={
    'STATION': 'STATION_ID',
    'Station_name': 'STATION',
    'Year': 'year',
    'Month': 'month',
    'Day': 'day',
    'Hour': 'hour',
    'Minute': 'minute',
    'temperature': 'HourlyDryBulbTemperature',
    'dew_point_temperature': 'HourlyDewPointTemperature',
    'wind_direction': 'HourlyWindDirection',
    'wind_speed': 'HourlyWindSpeed',
    'precipitation': 'HourlyPrecipitation',
    'visibility': 'HourlyVisibility'
}, inplace=True)

In [8]:
stations_to_keep = ['BAKERSFIELD AP', 'BEALE AFB', 'CASTLE AFB', 'FRESNO YOSEMITE INTL', 'LEMOORE REEVES NAS', 'REDDING AP', 'SACRAMENTO AP ASOS', 'SACRAMENTO MCCLELLAN AFB', 'SACRAMENTO MATHER AFB', 'SACRAMENTO METRO AP', 'STOCKTON AP', 'TRAVIS FLD AFB']

all_data = all_data[all_data['STATION'].isin(stations_to_keep)].reset_index(drop=True)

print(f"Filtered dataframe shape: {all_data.shape}")
print(all_data['STATION'].unique())

Filtered dataframe shape: (9293077, 16)
<StringArray>
[          'BAKERSFIELD AP',                'BEALE AFB',
               'CASTLE AFB',     'FRESNO YOSEMITE INTL',
       'LEMOORE REEVES NAS',               'REDDING AP',
       'SACRAMENTO AP ASOS',    'SACRAMENTO MATHER AFB',
 'SACRAMENTO MCCLELLAN AFB',      'SACRAMENTO METRO AP',
              'STOCKTON AP',           'TRAVIS FLD AFB']
Length: 12, dtype: str

In [9]:
all_data.head()

,STATION_ID,STATION,DATE,year,month,day,hour,minute,LATITUDE,LONGITUDE,HourlyDryBulbTemperature,HourlyDewPointTemperature,HourlyWindDirection,HourlyWindSpeed,HourlyPrecipitation,HourlyVisibility
0,USW00023155,BAKERSFIELD AP,1928-01-01 09:00:00,1928,1,1,9,0,35.4342,-119.0553,NaN,NaN,270.0,3.2,NaN,8.0
1,USW00023155,BAKERSFIELD AP,1928-01-01 12:00:00,1928,1,1,12,0,35.4342,-119.0553,NaN,NaN,270.0,0.5,NaN,8.0
2,USW00023155,BAKERSFIELD AP,1928-01-01 15:00:00,1928,1,1,15,0,35.4342,-119.0553,NaN,NaN,135.0,2.7,NaN,0.8
3,USW00023155,BAKERSFIELD AP,1928-01-01 16:00:00,1928,1,1,16,0,35.4342,-119.0553,NaN,NaN,90.0,1.4,NaN,0.8
4,USW00023155,BAKERSFIELD AP,1928-01-01 18:00:00,1928,1,1,18,0,35.4342,-119.0553,NaN,NaN,315.0,1.8,NaN,8.0

In [10]:
# Convert DATE from UTC to UTC-7
# does this add or subtract time from the original DATE? It subtracts 7 hours to convert from UTC to UTC-7.
all_data['DATE'] = all_data['DATE'] - pd.Timedelta(hours=7)

# Update hour, day, month, year columns to match the adjusted DATE
all_data['hour'] = all_data['DATE'].dt.hour
all_data['day'] = all_data['DATE'].dt.day
all_data['month'] = all_data['DATE'].dt.month
all_data['year'] = all_data['DATE'].dt.year

all_data.head()

,STATION_ID,STATION,DATE,year,month,day,hour,minute,LATITUDE,LONGITUDE,HourlyDryBulbTemperature,HourlyDewPointTemperature,HourlyWindDirection,HourlyWindSpeed,HourlyPrecipitation,HourlyVisibility
0,USW00023155,BAKERSFIELD AP,1928-01-01 02:00:00,1928,1,1,2,0,35.4342,-119.0553,NaN,NaN,270.0,3.2,NaN,8.0
1,USW00023155,BAKERSFIELD AP,1928-01-01 05:00:00,1928,1,1,5,0,35.4342,-119.0553,NaN,NaN,270.0,0.5,NaN,8.0
2,USW00023155,BAKERSFIELD AP,1928-01-01 08:00:00,1928,1,1,8,0,35.4342,-119.0553,NaN,NaN,135.0,2.7,NaN,0.8
3,USW00023155,BAKERSFIELD AP,1928-01-01 09:00:00,1928,1,1,9,0,35.4342,-119.0553,NaN,NaN,90.0,1.4,NaN,0.8
4,USW00023155,BAKERSFIELD AP,1928-01-01 11:00:00,1928,1,1,11,0,35.4342,-119.0553,NaN,NaN,315.0,1.8,NaN,8.0

In [11]:
#make sure values are numeric
numeric_cols = ['HourlyDryBulbTemperature','HourlyDewPointTemperature','HourlyWindDirection','HourlyWindSpeed','HourlyPrecipitation', 'HourlyVisibility']
all_data[numeric_cols] = all_data[numeric_cols].apply(pd.to_numeric, errors='coerce')
all_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9293077 entries, 0 to 9293076
Data columns (total 16 columns):
 #   Column                     Dtype
---  ------                     -----
 0   STATION_ID                 str
 1   STATION                    str
 2   DATE                       datetime64[us]
 3   year                       int32
 4   month                      int32
 5   day                        int32
 6   hour                       int32
 7   minute                     int64
 8   LATITUDE                   float64
 9   LONGITUDE                  float64
 10  HourlyDryBulbTemperature   float64
 11  HourlyDewPointTemperature  float64
 12  HourlyWindDirection        float64
 13  HourlyWindSpeed            float64
 14  HourlyPrecipitation        float64
 15  HourlyVisibility           float64
dtypes: datetime64[us](1), float64(8), int32(4), int64(1), str(2)
memory usage: 992.6 MB

In [12]:
# Fill NaN values for HourlyPrecipitation as 0
all_data['HourlyPrecipitation'] = all_data['HourlyPrecipitation'].fillna(0)

# show to check
all_data['HourlyPrecipitation'].head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: HourlyPrecipitation, dtype: float64

In [13]:
#cap HourlyVisibility values at 16
all_data['HourlyVisibility'] = all_data['HourlyVisibility'].clip(upper=16)

In [14]:
# If HourlyWindSpeed is equal to zero, set HourlyWindDirection to NaN
all_data.loc[all_data['HourlyWindSpeed'] == 0, 'HourlyWindDirection'] = np.nan

#print the rows where HourlyWindSpeed is zero to verify the change
print(all_data.loc[all_data['HourlyWindSpeed'] == 0, ['HourlyWindSpeed', 'HourlyWindDirection']])
all_data.shape

         HourlyWindSpeed  HourlyWindDirection
6                    0.0                  NaN
21                   0.0                  NaN
25                   0.0                  NaN
27                   0.0                  NaN
28                   0.0                  NaN
...                  ...                  ...
9292981              0.0                  NaN
9292982              0.0                  NaN
9292983              0.0                  NaN
9292984              0.0                  NaN
9293033              0.0                  NaN

[1465019 rows x 2 columns]

(9293077, 16)

In [15]:
# Print negative hourlywindspeed values
print(all_data.loc[all_data['HourlyWindSpeed'] < 0, ['HourlyWindSpeed', 'HourlyWindDirection']])
all_data.shape

Empty DataFrame
Columns: [HourlyWindSpeed, HourlyWindDirection]
Index: []

(9293077, 16)

In [16]:
# If HourlyWindSpeed is equal to NaN, set HourlyWindDirection to NaN
all_data.loc[all_data['HourlyWindSpeed'].isna(), 'HourlyWindDirection'] = np.nan

#print the rows where HourlyWindSpeed is NaN to verify the change
print(all_data.loc[all_data['HourlyWindSpeed'].isna(), ['HourlyWindSpeed', 'HourlyWindDirection']])
all_data.shape

         HourlyWindSpeed  HourlyWindDirection
24                   NaN                  NaN
26                   NaN                  NaN
29                   NaN                  NaN
30                   NaN                  NaN
31                   NaN                  NaN
...                  ...                  ...
9287239              NaN                  NaN
9288196              NaN                  NaN
9289064              NaN                  NaN
9289993              NaN                  NaN
9289994              NaN                  NaN

[386878 rows x 2 columns]

(9293077, 16)

In [ ]:
# # Save as CSV
# all_data.to_csv('cleaned_data_Oct3.csv', index=False)