In [1]:

# importing needed packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#read in csv
sac_data = pd.read_csv("sacstation1.csv")

/var/folders/_r/k4drv0q16vb4s0cfjxzhbc180000gn/T/ipykernel_53782/4161668466.py:2: DtypeWarning: Columns (9,10,11,12,13,14,17,18,19,20,25,28,46,47,48,49,50,58,59) have mixed types. Specify dtype option on import or set low_memory=False.
  sac_data = pd.read_csv("sacstation1.csv")

In [3]:
sac_data.head(5)

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,REPORT_TYPE,SOURCE,CoolingDegreeDaysSeasonToDate,DailyAverageDryBulbTemperature,...,MonthlyNumberDaysWithSnowfall,MonthlyNumberDaysWithThunderstorms,MonthlyTotalLiquidPrecipitation,MonthlyTotalSnowfall,NormalsCoolingDegreeDay,NormalsHeatingDegreeDay,REPORT_TYPE.1,SOURCE.1,Sunrise,Sunset
0,USW00023271,"SACRAMENTO 5 ESE, CA US",38.5552,-121.4183,11.6,1877-07-11T00:00:00,SOD,NaN,NaN,25.9,...,NaN,NaN,NaN,NaN,NaN,NaN,SOD,NaN,450.0,1932.0
1,USW00023271,"SACRAMENTO 5 ESE, CA US",38.5552,-121.4183,11.6,1877-07-12T00:00:00,SOD,NaN,NaN,29.7,...,NaN,NaN,NaN,NaN,NaN,NaN,SOD,NaN,451.0,1931.0
2,USW00023271,"SACRAMENTO 5 ESE, CA US",38.5552,-121.4183,11.6,1877-07-13T00:00:00,SOD,NaN,NaN,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,SOD,NaN,451.0,1931.0
3,USW00023271,"SACRAMENTO 5 ESE, CA US",38.5552,-121.4183,11.6,1877-07-14T00:00:00,SOD,NaN,NaN,29.5,...,NaN,NaN,NaN,NaN,NaN,NaN,SOD,NaN,452.0,1930.0
4,USW00023271,"SACRAMENTO 5 ESE, CA US",38.5552,-121.4183,11.6,1877-07-15T00:00:00,SOD,NaN,NaN,27.2,...,NaN,NaN,NaN,NaN,NaN,NaN,SOD,NaN,453.0,1930.0

In [4]:
# print all column names
for col in sac_data.columns:
    print(col)

STATION
NAME
LATITUDE
LONGITUDE
ELEVATION
DATE
REPORT_TYPE
SOURCE
CoolingDegreeDaysSeasonToDate
DailyAverageDryBulbTemperature
DailyCoolingDegreeDays
DailyDepartureFromNormalAverageTemperature
DailyHeatingDegreeDays
DailyMaximumDryBulbTemperature
DailyMinimumDryBulbTemperature
DailyPeakWindDirection
DailyPeakWindSpeed
DailyPrecipitation
DailySnowDepth
DailySnowfall
DailyWeather
HeatingDegreeDaysSeasonToDate
HourlyDewPointTemperature
HourlyDryBulbTemperature
HourlyPrecipitation
HourlyPresentWeatherType
HourlyRelativeHumidity
HourlySeaLevelPressure
HourlySkyConditions
HourlyStationPressure
HourlyWetBulbTemperature
HourlyWindDirection
HourlyWindSpeed
MonthlyCoolingDegreeDays
MonthlyDaysWithGT001Precip
MonthlyDaysWithGT010Precip
MonthlyDaysWithGT32Temp
MonthlyDaysWithGT90Temp
MonthlyDaysWithLT0Temp
MonthlyDaysWithLT32Temp
MonthlyDepartureFromNormalAverageTemperature
MonthlyDepartureFromNormalCoolingDegreeDays
MonthlyDepartureFromNormalHeatingDegreeDays
MonthlyDepartureFromNormalMaximumTemperature
MonthlyDepartureFromNormalMinimumTemperature
MonthlyDepartureFromNormalPrecipitation
MonthlyGreatestPrecip
MonthlyGreatestPrecipDate
MonthlyGreatestSnowDepth
MonthlyGreatestSnowfall
MonthlyGreatestSnowfallDate
MonthlyHeatingDegreeDays
MonthlyMaximumTemperature
MonthlyMeanTemperature
MonthlyMinimumTemperature
MonthlyNumberDaysWithHeavyFog
MonthlyNumberDaysWithSnowfall
MonthlyNumberDaysWithThunderstorms
MonthlyTotalLiquidPrecipitation
MonthlyTotalSnowfall
NormalsCoolingDegreeDay
NormalsHeatingDegreeDay
REPORT_TYPE.1
SOURCE.1
Sunrise
Sunset

In [5]:
#select columns of relevant interest
selected_sac_columns = ["STATION", "NAME", "DATE", "REPORT_TYPE", "HourlyDryBulbTemperature", "HourlyPrecipitation", "HourlySkyConditions","MonthlyNumberDaysWithHeavyFog"]

selected_sac_data = sac_data[selected_sac_columns]
selected_sac_data

,STATION,NAME,DATE,REPORT_TYPE,HourlyDryBulbTemperature,HourlyPrecipitation,HourlySkyConditions,MonthlyNumberDaysWithHeavyFog
0,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-11T00:00:00,SOD,NaN,NaN,NaN,NaN
1,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-12T00:00:00,SOD,NaN,NaN,NaN,NaN
2,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-13T00:00:00,SOD,NaN,NaN,NaN,NaN
3,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-14T00:00:00,SOD,NaN,NaN,NaN,NaN
4,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-15T00:00:00,SOD,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
113599,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-29T00:00:00,SOD,NaN,NaN,NaN,NaN
113600,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-30T00:00:00,SOD,NaN,NaN,NaN,NaN
113601,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-31T00:00:00,SOD,NaN,NaN,NaN,NaN
113602,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-31T23:59:00,SOM,NaN,NaN,NaN,NaN
113603,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-06-01T00:00:00,SOD,NaN,NaN,NaN,NaN

In [10]:
# Look at missing values
missing_data_rows = selected_sac_data[selected_sac_data.isna().any(axis=1)]
missing_data_rows

,STATION,NAME,DATE,REPORT_TYPE,HourlyDryBulbTemperature,HourlyPrecipitation,HourlySkyConditions,MonthlyNumberDaysWithHeavyFog
0,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-11T00:00:00,SOD,NaN,NaN,NaN,NaN
1,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-12T00:00:00,SOD,NaN,NaN,NaN,NaN
2,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-13T00:00:00,SOD,NaN,NaN,NaN,NaN
3,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-14T00:00:00,SOD,NaN,NaN,NaN,NaN
4,USW00023271,"SACRAMENTO 5 ESE, CA US",1877-07-15T00:00:00,SOD,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
113599,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-29T00:00:00,SOD,NaN,NaN,NaN,NaN
113600,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-30T00:00:00,SOD,NaN,NaN,NaN,NaN
113601,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-31T00:00:00,SOD,NaN,NaN,NaN,NaN
113602,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-05-31T23:59:00,SOM,NaN,NaN,NaN,NaN
113603,USW00023271,"SACRAMENTO 5 ESE, CA US",2025-06-01T00:00:00,SOD,NaN,NaN,NaN,NaN

In [13]:
just_columns = ["HourlyDryBulbTemperature", "HourlyPrecipitation", "HourlySkyConditions","MonthlyNumberDaysWithHeavyFog"]

columns_sac_data = sac_data[just_columns]
columns_sac_data

,HourlyDryBulbTemperature,HourlyPrecipitation,HourlySkyConditions,MonthlyNumberDaysWithHeavyFog
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN
...,...,...,...,...
113599,NaN,NaN,NaN,NaN
113600,NaN,NaN,NaN,NaN
113601,NaN,NaN,NaN,NaN
113602,NaN,NaN,NaN,NaN
113603,NaN,NaN,NaN,NaN

In [14]:
#all of them????
other_data_rows = columns_sac_data[columns_sac_data.notna().any(axis=1)]
print(other_data_rows)

        HourlyDryBulbTemperature  HourlyPrecipitation HourlySkyConditions  \
5829                         5.6                  NaN                 NaN
5830                         5.6                  NaN                 NaN
5831                         7.3                  NaN                 NaN
5832                         7.3                  NaN                 NaN
5834                         4.4                  NaN                 NaN
...                          ...                  ...                 ...
113193                       NaN                  0.5                 NaN
113309                       NaN                  0.3                 NaN
113310                       NaN                  0.3                 NaN
113311                       NaN                  0.3                 NaN
113312                       NaN                  0.3                 NaN

        MonthlyNumberDaysWithHeavyFog
5829                              NaN
5830                              NaN
5831                              NaN
5832                              NaN
5834                              NaN
...                               ...
113193                            NaN
113309                            NaN
113310                            NaN
113311                            NaN
113312                            NaN

[57325 rows x 4 columns]

In [15]:


just_fog = sac_data["MonthlyNumberDaysWithHeavyFog"]
print(just_fog)

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
113599   NaN
113600   NaN
113601   NaN
113602   NaN
113603   NaN
Name: MonthlyNumberDaysWithHeavyFog, Length: 113604, dtype: float64

In [17]:
just_fog_rows = just_fog[just_fog.notna()]
print(just_fog_rows)

110362    1.0
Name: MonthlyNumberDaysWithHeavyFog, dtype: float64